### ISSUE TITLE
TrailingWhitescpace rule doesn't work on windows

### ISSUE THREAD

**Issue by xav9211** [CodeNarc/CodeNarc#298] opened 2018-01-02 10:24 UTC
I use CodeNarc with gradle. There is problem with trailingWhitespace rule, on linux system it finds whitespaces on the end of line, but running build on windows it doesn't find these whitespaces.

**Comment by erdi** [comment] 2018-01-02 10:30
I believe this is a duplicate of #279.

**Closed** 2018-01-02 10:32 UTC
