### ISSUE TITLE
`ClosureAsLastMethodParameter` issue

### ISSUE THREAD

**Issue by modestukasai** [CodeNarc/CodeNarc#328] opened 2018-03-12 10:30 UTC
I get error when method is called, that it can be used without parenthesis
```
calculateSmth(Bean1 request1, Bean2 request2)

            1 * service.calculateSmth({ Bean1 request1 ->
                request1.type == MAIN  } as Bean1,
             { Bean2 request2 -> request2.type == MAIN  } as Bean2) == 0.50

Violation in class xxxx. The last parameter to the 'someMethod' method call is a closure an can appear outside the parenthesis
```

**Comment by modestukasai** [comment] 2018-03-12 10:43
Also easy example with 
```
[].sort(false, { a, b -> a <=> b }).first()

Violation in class xxxx. The last parameter to the 'someMethod' method call is a closure an can appear outside the parenthesis
```

**Comment by chrismair** [comment] 2018-04-04 19:13
The violation for your 2nd example is legitimate, as it could be rewritten:
`[].sort(false) { a, b -> a <=> b }.first()`

**Comment by chrismair** [comment] 2018-04-04 21:04
I am unable to reproduce the violation for the code in the 1st example. I am using CodeNarc 1.1 with Groovy 2.3/2.4 and Java 1.8. Are you perhaps using older CodeNarc? Or is the actual code different, since I see no "someMethod" in the example?

**Comment by chrismair** [comment] 2018-06-16 01:17
Closing. Feel free to reopen if still relevant.

**Closed by chrismair** 2018-06-16 01:17 UTC
