### ISSUE TITLE
Spock data table is recognized as boolean expression 

### ISSUE THREAD

**Issue by modestukasai** [CodeNarc/CodeNarc#361] opened 2018-09-05 08:36 UTC
Hi,
I'm getting `UnnecessaryBooleanExpression` for below case:
```
@Unroll
    def 'should do something' {
        expect:
            doSomethingWithCountryCode(countryCode) == expectedResult
        where:
            countryCode | expectedResult
            'se'        || 'success'
            'sE'        || 'wrongStuff'
            ' se '      || 'blablabla'
    }
```

**Comment by chrismair** [comment] 2018-09-05 23:15
This looks like a duplicate of issue #329.

**Comment by jlstrater** [comment] 2018-10-12 08:52
Yes, it's a duplicate. Can we close this one?

**Comment by chrismair** [comment] 2018-10-13 23:12
Closing as duplicate

**Closed by chrismair** 2018-10-13 23:12 UTC
