### ISSUE TITLE
`UnnecessaryGetter` issue

### ISSUE THREAD

**Issue by modestukasai** [CodeNarc/CodeNarc#330] opened 2018-03-12 11:15 UTC
Issue when using spock stubs. If not method is used, test fails...
```
product = Stub(Product) {
                getId() >> 10
            }
```

```
getId() >> 10

[MSG]Violation in class XXX. getId() can probably be rewritten as id
```

**Comment by boris-petrov** [comment] 2018-04-18 15:07
This is duplicate of https://github.com/CodeNarc/CodeNarc/issues/235.

**Comment by chrismair** [comment] 2018-05-02 00:06
Fixed under #235. Available in CodeNarc 1.2.

**Closed by chrismair** 2018-05-02 00:06 UTC
